### ISSUE TITLE
Relocate per-cluster app of apps to argocd-apps

### ISSUE THREAD

**Issue by tumido** [operate-first/argocd-apps#115]
I wonder, can we move the app of apps to the `argocd-apps` repo? So adding a cluster would be only PRs against 2 repos, instead of 3?

_Originally posted by @tumido in https://github.com/operate-first/apps/issues/419#issuecomment-804959773_

Right now it's not that straightforward to add a new cluster to ArgoCD. 3 PRs are minimal. If we can remove once step, it would be a huge improvement.

**Comment by HumairAK** [comment]
I think this is a good idea, but there's the chicken and egg problem. The app-of-apps deploys apps in the `argocd-apps` repo, but if those are apps are in the `argocd-apps` repo, then what deploys those apps? an `app-of-app-of-apps`? I think I would like to avoid that. If the problem is needing to touch too many repos, what we can instead do is: 

create a new directory at root called `app-of-apps` so it would look like: 

```
argocd-apps/
- docs/
- envs/
- app-of-apps/     # new dir
   |- kustomization.yaml
```

Now we just put all our app-of-apps in this dir and add it to app-of-apps/kustomization.yaml and remote reference this from the `continuous-deployment` repo? wdyt?

**Comment by tumido** [comment]
I think the remote reference in `continuous-deployment` is a way to go. It would consolidate all apps (including app of apps) into a single repo and make it more consistent. I like that.

**Comment by HumairAK** [comment]
stale issue, closing -- reopen in apps repo if needed
