### ISSUE TITLE
Move argocd-apps repo content to apps repo

### ISSUE THREAD

**Issue by HumairAK** [operate-first/argocd-apps#216]
I don't see any real benefit to having `argocd-apps` be its own separate repo. It's also annoying making 2 prs everytime a new app is added. WDYT about moving this repo's contents to root folder of `apps` in an `argocd-apps` folder?

**Comment by HumairAK** [comment]
@tumido @4n4nd

**Comment by larsks** [comment]
I think this is a great idea (and we've done exactly this with the MOC apps repository).

**Comment by tumido** [comment]
I don't mind it. I think any simplification helps. I think it can help us with transition to the gitops operator as well.

I'd name the folder `argocd` instead of `argocd-apps` so the future integration with gitops operator is even more obvious. also it's not just apps but also projects and other configs... So let's get rid of the `-apps` in the name of the folder WDYT?

**Comment by 4n4nd** [comment]
> I'd name the folder argocd instead of argocd-apps so the future integration with gitops operator is even more obvious. also it's not just apps but also projects and other configs... So let's get rid of the -apps in the name of the folder WDYT?

I like that idea :+1: 

and since argocd is one of the apps that is available on operate-first, we won't need to restructure everything else
